server:
  port: 9696
        
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlineshopping
    username: root
    password: rootroot
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: syedafaheem7@gmail.com
    password: azgxoeohqcsjnbkz
    properties:
     mail:
      smtp:
       starttls:
         enable: true

app.admin.email: admin@gmail.com
     